### ISSUE TITLE
Add chapter name at the top

### ISSUE THREAD

**Issue by mikecjtio** [TimeblurStudio/Osmoscape#17]
We need to indicate the chapter name after scrolling stops.

**Comment by shreyaansjain** [comment]
I have completed the code 80% but at one position i am stuck it will be great if you help on which element i should show chapter name i used .nav but its giving text on botton also i used on main-scroll-canvas but nothing happen please help me in it

**Comment by mikecjtio** [comment]
> I have completed the code 80% but at one position i am stuck it will be great if you help on which element i should show chapter name i used .nav but its giving text on botton also i used on main-scroll-canvas but nothing happen please help me in it

The [nav section](https://github.com/TimeblurStudio/Osmoscape/blob/54b1acea91fc9883573485d0db2d5772e3a66117/app/src/index.html#L87) is mainly to hold the icons and is positioned at the bottom, you do not have to change that.

Currently, there is no paragraph to show chapter name inside [index.html](https://github.com/TimeblurStudio/Osmoscape/blob/master/app/src/index.html).

You'll need to add an element at the top left of the screen and then change the text using jquery - https://www.tutorialspoint.com/How-to-change-text-inside-an-element-using-jQuery

You can add the element inside or outside [head-actions div](https://github.com/TimeblurStudio/Osmoscape/blob/54b1acea91fc9883573485d0db2d5772e3a66117/app/src/index.html#L105) in index.html but make sure the paragraph is positioned at the top left of the screen.
You can momentarily hide FPS meter if it's overlapping or you can add some more margin to FPS meter at this [line](https://github.com/TimeblurStudio/Osmoscape/blob/54b1acea91fc9883573485d0db2d5772e3a66117/app/src/scripts/main.js#L32).

**Comment by shreyaansjain** [comment]
Thanks for your reply i have completed it now and is working fine but it gives some error in console  can you help me resolving that error i tried but not able to resolve any help or reference will be appreciated

**Comment by shreyaansjain** [comment]
<img width="1440" alt="Screenshot 2021-08-28 at 2 17 53 PM" src="https://user-images.githubusercontent.com/86606251/131212227-3760815a-2df8-425f-b8a5-3cf6fa9d6ad0.png">

**Comment by shreyaansjain** [comment]
Should i share the screenshots of changes i have made?

**Comment by mikecjtio** [comment]
Thanks for the changes. 

Screenshot might not be necessary, You can create a pull request on GitHub and I'll verify the code before publishing.

A small input, it'd be great if you can make the colour of the text as white.

**Comment by shreyaansjain** [comment]
Sure

**Comment by mikecjtio** [comment]
Just a style property in the HTML file on the element should be okay too.

**Comment by shreyaansjain** [comment]
I made the pull request kindly check it and if you want some changes please tell me I am ready to that

**Comment by shreyaansjain** [comment]
Please review the mine pull request and merge it

**Comment by mikecjtio** [comment]
Thanks  for this update @shreyaansjain06. I've closed this issue now after merging your code.
